version: '3.1'

services:
  srv_gin:
    build: 
      context: .
      args:
        - SRC=${SRCDIR}
        - LOG=${LOGDIR}
        - RUN=${RUNDIR}
        - ETC=${ETCDIR}
        - BIN=${BINDIR}
        - APPNAME=${APPNAME}
    ports:
      - 8081:8080 
    volumes:
      - .:${SRCDIR}
    environment:
      - FLOG=0
      - SILENT=0
      - GINMODE=DEBUG
      - AMQP_SERVER=srv_rabbit
      - AMQP_LOGIN=eensyiot-admin:33n5y4dm1n
      - AMQP_QNAME=config-alerts
      # - AMQP_LOGIN=eensyiot-admin:33n5y4dm1u
    secrets:
      - db_root_username
      - db_root_password
    container_name: ctn_web 
    stdin_open: true
    networks:
      - eensyaqp-nw
    depends_on:
      srv_mongo:
        condition: service_healthy
      srv_rabbit:
        condition: service_healthy
    entrypoint: ["${BINDIR}/${APPNAME}"]
  srv_mongo:
    image: mongo:4.2-bionic
    command: [--auth]
    secrets:
      - db_root_username
      - db_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    volumes: 
      - /data/eensyaquap/mongo:/data/db
    ports:
      - 57017:27017
    networks:
    - eensyaqp-nw
    container_name: ctn_mongo
    tty: true
    stdin_open: true
    healthcheck:
      test: "exit 0"
  srv_rabbit:
    image: rabbitmq:3.13-rc-management
    ports:
      - 35672:15672
      - 5672:5672
    networks:
      - eensyaqp-nw
    environment:
      - RABBITMQ_DEFAULT_USER=eensyiot-admin
      - RABBITMQ_DEFAULT_PASS=33n5y4dm1n
    stdin_open: true 
    container_name: ctn_rabbit
    healthcheck:
      test: "exit 0"
networks:
  eensyaqp-nw:
      driver: bridge
secrets:
  db_root_username:
    file: ./db_root_username.secret
  db_root_password:
    file: ./db_root_password.secret
  