### simple new user insert test
POST  http://localhost:8081/api/users
Content-Type: application/json

{
    "email": "kneerunjun@gmail.com",
    "auth": "jun%41993",
    "telegid":645645677,
    "role":0,
    "name": "Niranjan Awati"

}

### Simple patch requesst for the existing user

PATCH  http://localhost:8081/api/users/66042fc255e438864127511b
content-type: application/json

{
    "email": "kneerunjun@gmail.com",
    "auth": "radaa%41993",
    "telegid":645645699
}



### simple authentication test 
POST http://localhost:8081/api/login
content-type: application/json

{
    "email": "kneerunjun@gmail.com",
    "auth": "radaa%41993"
}


### Deleting the user account

DELETE   http://localhost:8081/api/users/kneerunjun@gmail.com
