### simple new user insert test
POST  http://localhost:8081/api/users
Content-Type: application/json

{
    "email": "kneerunjun@gmail.com",
    "auth": "jun%41993",
    "telegid":645645677,
    "role":0,
    "name": "Niranjan Awati"
}

### Simple patch requesst for the existing user

PATCH  http://localhost:8081/api/users/6604ade011e8c491e94eb022
content-type: application/json

{
    "email": "kneerunjun@gmail.com",
    "auth": "jenc%41993",
    "name": "Niranjan Vijay Awati",
    "telegid":645645699
}



### simple authentication test 
POST http://localhost:8081/api/login
content-type: application/json

{
    "email": "kneerunjun@gmail.com",
    "auth": "jun%41993"
}

### simple authorize request, sends the token to get an http status code

GET http://localhost:8081/api/authorize
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTIwMDE1MzAsImlzcyI6InBhdGlvLXdlYiBzZXJ2ZXIiLCJzdWIiOiJVc2VyIGF1dGhvcml6YXRpb24gcmVxdWVzdCIsInVzZXIiOiJrbmVlcnVuanVuQGdtYWlsLmNvbSIsInVzZXItcm9sZSI6MH0.1y4Jh7OC-YCivaxYXeEPdbTNbdAB6LiiHkHiBjQWoRE

### Deleting the user account

DELETE   http://localhost:8081/api/users/kneerunjun@gmail.com


### getting one device information 

GET http://localhost:8081/api/devices/45-36-17-E3-1C-71

### deleting the existing device
DELETE http://localhost:8081/api/devices/45-36-17-E3-1C-71

### adding a new device to the database 
POST http://localhost:8081/api/devices/
content-type: application/json

{
    "mac":"45-36-17-E3-1C-71",
    "make": "raspberry pi 0w 512 MB",
    "name": "Pump control, saidham",
    "users": ["kneerunjun@gmail.com"]
}


### simple user add to the list of device owners

PATCH  http://localhost:8081/api/devices/45-36-17-E3-1C-71/users
content-type: application/json

{
    "users": ["niranjanawati@gmail.com"]
}