apiVersion: v1
kind: Service
metadata:
 name: svc-webaqua
spec:
 type: NodePort
 ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
    protocol: TCP
 selector:
  app: web-aquaponics
  type: gogin 